#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: 社会的選択理論勉強会
#+date: <2022-09-02 金>
#+author: Hisanobu Nakamura
#+email: hisanobu@pop-os
#+language: ja
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.3)

* 社会的選択理論への招待　坂井豊貴
社会的選択理論の入門書

** 本書の構成
- 第1章：ボルダとコンドル背による議論を紹介
  - ボルダの論文とコンドルセによる議論
- 第２章：コンドルセによる統計学的な議論について扱う。
  - 陪審定理について扱う。本書以外で、他に詳しい解説が見当たらないらしい。
- 第３章：多数決の代替案として、ボルダルールが望ましいという議論をする。
  - 他の代替案なしで安易に批判するものが少なくないが、ここでされる肯定的な議論を踏まえていないものが多い
  - この章の議論は主に1970年代になされたものだが、専門家の間でも十分に認識されているとは言い難く、再評価がなされてよいものだと筆者は言っている
- 第4章：政治と選択
  - ダンカン・ブラック(Duncan Black https://en.wikipedia.org/wiki/Duncan_Black)
    - 単峰性という条件が成り立つときはペア全勝者が存在することを発見。
    - 社会科学全般へのインパクトが大きかった。実証政治理論とメカニズムデザインという分野を生み出すきっかけとなった
- 第5章：ケネス・アローが考案した二項独立性という条件を中心に論じる。
  - コンドルセはペアごとに選択肢を比較することにこだわったが、アローはその姿勢を徹底追及して、飛行独立性という条件を定式化して議論を展開した
  - アローは、一般には二項独立性を尊重し切ることはできないという不可能性定理と、単峰性が成り立つときにはその不可能性が回避できるという可能性定理をともに示した。
    - 本書では、有権者数と選択肢がともに３であるケースについて詳細な証明を与える
- 第６章：社会状態の良し悪しを判定する基準である、社会構成基準について論じる。
  - 功利主義基準、ナッシュ基準、マキシミン基準、レキシミン基準などを比較検討
  - アローの不可能性定理再び。アマルティア・センの自由主義のパラドックス、ロールズ流の正義論に基づく解消の考察
- 第７章：社会的選択理論と人民主権社会を絡めて論じる。時事的なテーマ。

** 本書の特徴
社会的選択理論の教科書で、ボルダとコンドルセの古典から議論を立ち上げていく構成を取ったものはおそらく他にない。

現在、社会的選択理論というときには、
1) 投票における意思集約方法の設計
2) 社会状態の望ましさを評価する基準の構築

を主に含むことが多い。
本書は1) に軸足を置いているが、第６章で 2) についても詳しく扱う。日本で出版されている社会的選択理論の本は2)を重視する傾向が強く、1)を重視する書籍は珍しい。

* 第１章　問題の出発点
** 1.1.1 ボルダルールの提案
1770年にジャン＝シャルル・ド・ボルダ(Jean-Charles de Borda, 1733-1799)はパリ王立科学アカデミー(Académie des sciences)において、多数決という意思集約方法の本質的な欠陥に関する研究報告を行った。

冒頭パラグラフ：
#+begin_quote
「投票において再多数票を得た選択肢は、常に人々の意思を表していると一般に考えられているようで、私はそれに関する論争を聞いたことがない。つまりそうした選択肢は、他の選択肢よりも有権者からz好まれているはずだというわけである。
しかし私はこうした考えが、選択肢が２個しかないケースを除いては成立しないことを明らかにしていく。」
#+end_quote
有権者数:２１人 \\
選択肢: {x,y,z} (政策、候補者etc) \\
有権者が以下のような順序をつけているとする。\\

|     | 4 人 | 4 人 | 7 人 | 6 人 |
|-----+------+------+------+------|
| /   | <>   | <>   | <>   |<>    |
| 1位 | $x$  | $x$  | $y$  | $z$  |
| 2位 | $y$  | $z$  | $z$  | $y$  |
| 3位 | $z$  | $y$  | $x$  | $x$  |


これらの順序に基づき、一人の有権者が１枚の投票用紙を与えられ１つの選択肢を書く、 *単記式* の多数決を行えば

- ８票が $x$
- 7票が $y$
- 6票が $z$

に入り、 $x$ が勝つ。このように多数決でかつ選択肢のことを多数決勝者と呼ぶ。

ここで問題だが、$x$ は他の選択肢と比して有権者から高く評価されているといえるのだろうか？
実際、$x$ と $y$ だけをペアで比較してみると

- 8人が $x$ を $y$ より
- 13人が $y$ を $x$ より

高く評価しており、過半数のものは $y$ を $x$ より高く評価している。
また、 $x$ と $z$ だけをペアで比較してみても、同様に

- 8人が $x$ を $z$ より
- 13人が $z$ を $x$ より

高く評価しており、過半数のものは $z$ を $x$ より高く評価している。

つまり、 $x$ は $y$ にも $z$ にもペア毎の多数決で負ける選択肢である。

にも関わらずxが全体での多数決で勝てるのは、2つの選択肢yとzについて票が割れているからに他ならない。

このことをボルダは「2人のアスリートが競い疲れきってしまった後で、第3の最も弱い者に負けてしまうようなものだ」と表現した。

この観点から多数決に疑問を呈したボルダは次の *ボルダルール* と呼ばれるルールを考察した。

ボルダルール：各選択肢への順位をすべて書き、それに応じて加点し和を取る。選択肢の数が３つなら、1位に3点、2位に2点、3位に1点というように加点する。

今の例での得点和はそれぞれ

- $x$ の得点: $3\cdot 8 + 2 \cdot 0 + 1 \cdot 13 = 37$
- $y$ の得点: $3\cdot 7 + 2 \cdot 10 + 1 \cdot 4 = 45$
- $z$ の得点: $3\cdot 6 + 2 \cdot 11 + 1 \cdot 4 = 44$

となる。  

こうした得点和を *ボルダ得点* と呼び、 $p(x) = 37$ 、$p(y) = 45$ 、$p(z) = 44$ のように表す。
また、ボルダ得点が最大になる選択肢をボルダ勝者と呼ぶ。ここでのぼるだ勝者は $y$ である。

$x$ は、ペア全敗者と呼ぶことにする。

ボルダの論文では、「多数決がペア全敗者を選びうる」ことを指摘してから、ボルダルールを導入しているが、ボルダルールがペア全敗者を選ばないことの証明は書かれていない。
実際の証明が与えられたのは200年後。

*Theorem* ボルダ勝者はペア全敗者ではない。\\
*[Proof]*\\
今、次の状況を考える。
- 有権者：クロ、タマ、ポチ
- 選択肢: $x,y,z$
- 一人一人の有権者はそれぞれ、1位の選択肢に3点、2位に2点、3位に1点を加点する。
一般の場合も、同様の手法で証明できる（らしい）。

まず、
\begin{equation}
\label{eq:1}
p(x) + p(y) + p(z) = 18
\end{equation}

である。
今、$x$ をボルダ勝者とする、すなわち、$p(x) \ge p(y)$ かつ、 $p(x) \ge p(z)$ が成り立つとする。

このとき、$x$ はペア全敗者でありえないことを示す。

明らかに、
\begin{equation}
\label{eq:2}
p(x) \ge \frac{p(x)+p(y)+p(z)}{3} = 6
\end{equation}

が成り立つ。6点以上獲得するということは、$x$ は最悪でも
|          | クロ | タマ    | ポチ    |
|----------+------+---------+---------|
| /        | <>   | <>      | <>      |
| 1位(3点) | $x$  | $\star$ | $\star$ |
| 2位(2点) |      | $x$     | $\star$ |
| 3位(1点) |      |         | $x$     |

という順序付けや
|          | クロ    | タマ    | ポチ    |
|----------+---------+---------+---------|
| /        | <>      | <>      | <>      |
| 1位(3点) | $\star$ | $\star$ | $\star$ |
| 2位(2点) | $x$     | $x$     | $x$     |
| 3位(1点) |         |         |         |

という、$\star$ が3つしかないような順序付けになっているはずである。

もし、$\star$ が、４つ以上あると、 $p(x) < 6$ となるからである。

ここで、$x$ がペア全敗者であると仮定する。すなわち、ペア同士の多数決で $y$ 、 $z$ ともに $x$ に勝利することになる。

そのためには
|          | クロ | タマ | ポチ |
|----------+------+------+------|
| /        | <>   | <>   | <>   |
| 1位(3点) | $y$  | $z$  | $x$  |
| 2位(2点) | $z$  | $y$  |      |
| 3位(1点) | $x$  | $x$  |      |
や、
|          | クロ | タマ | ポチ |
|----------+------+------+------|
| /        | <>   | <>   | <>   |
| 1位(3点) | $y$  | $z$  | $z$  |
| 2位(2点) | $x$  | $x$  | $y$  |
| 3位(1点) |      |      | $x$  |

という順序付けが成り立たなければならない。
すなわち、 $x$ がペア全敗者であるためには、 テーブル上で $x$ より上に位置する選択肢が4個以上必要ということになる。
しかし、これは $p(x) \ge 6$ と矛盾する。よって、ボルダ勝者 $x$ は、ペア全敗者ではありえない。 $\square$
** 1.1.2 ボルダ勝者と過半数有権者
今、5人の有権者がいる次の例を考えてみる：
|          | クロ | タマ | ポチ | ゴマ | ケロ |
|----------+------+------+------+------+------|
| /        | <>   | <>   | <>   | <>   | <>   |
| 1位(3点) | $y$  | $y$  | $y$  | $x$  | $x$  |
| 2位(2点) | $x$  | $x$  | $x$  | $z$  | $z$  |
| 3位(1点) | $z$  | $z$  | $z$  | $y$  | $y$  |

すると、$p(x)=12$ 、 $p(y)=11$ 、 $p(z)=7$ なので $x$ がボルダ勝者となる。

しかし、多数決勝者は $y$ であり、過半数の有権者が $y$ を $x$ より高く順序付けている。

つまり
- ボルダ勝者 $x$ と多数決勝者 $y$ が異なる。
- 過半数のものは $y$ を $x$ より好んでいる。
これは、ボルダルールと多数決の間に大きな対立が生じていると言える。

ボルダ「いったい多数決勝者が、ボルダ勝者でもあると *断定できる* のはどの程度の票を集めたときか？」

上の例のように、5人の有権者と3つの選択肢がある状況では、3票を得るだけでは、その選択肢がボルダ勝者だと断定することはできない。

4票ではどうだろうか？例えば、$y$ が下のように多数決で4票得たとしよう

|          | クロ | タマ | ポチ | ゴマ | ケロ |
|----------+------+------+------+------+------|
| /        | <>   | <>   | <>   | <>   | <>   |
| 1位(3点) | $y$  | $y$  | $y$  | $y$  | $x$  |
| 2位(2点) | ?    | ?    | ?    | ?    | ?    |
| 3位(1点) | ?    | ?    | ?    | ?    | ?    |

$y$ にとって、起こりうる最悪のケースは

|          | クロ | タマ | ポチ | ゴマ | ケロ |
|----------+------+------+------+------+------|
| /        | <>   | <>   | <>   | <>   | <>   |
| 1位(3点) | $y$  | $y$  | $y$  | $y$  | $x$  |
| 2位(2点) | $x$  | $x$  | $x$  | $x$  | ?    |
| 3位(1点) | ?    | ?    | ?    | ?    | $y$  |

である。しかし、このケースでさえ

\begin{equation}
\label{eq:3}
p(y) = 13 > 11 = p(x)
\end{equation}

なので、$y$ は多数決勝者でもあり、ボルダ勝者でもある。

選択肢を増やしてみたらどうだろうか？

有権者5人、選択肢6つで考えてみよう。以下の得票状況を考える

|          | クロ | タマ | ポチ | ゴマ | ケロ |
|----------+------+------+------+------+------|
| /        | <>   | <>   | <>   | <>   | <>   |
| 1位(6点) | $y$  | $y$  | $y$  | $x$  | $x$  |
| 2位(5点) | ?    | ?    | ?    | ?    | ?    |
| 3位(4点) | ?    | ?    | ?    | ?    | ?    |
| 4位(3点) | ?    | ?    | ?    | ?    | ?    |
| 5位(2点) | ?    | ?    | ?    | ?    | ?    |
| 6位(1点) | ?    | ?    | ?    | ?    | ?    |

このとき、$y$ がボルダ勝者であると断定する事は可能だろうか。

|          | クロ | タマ | ポチ | ゴマ | ケロ |
|----------+------+------+------+------+------|
| /        | <>   | <>   | <>   | <>   | <>   |
| 1位(6点) | $y$  | $y$  | $y$  | $x$  | $x$  |
| 2位(5点) | ?    | ?    | ?    | ?    | ?    |
| 3位(4点) | ?    | ?    | ?    | ?    | ?    |
| 4位(3点) | ?    | ?    | ?    | ?    | ?    |
| 5位(2点) | ?    | ?    | ?    | ?    | ?    |
| 6位(1点) | ?    | ?    | ?    | ?    | $y$  |
であり、
\begin{equation}
\label{eq:4}
p(y) = 25 < 26 = p(x)
\end{equation}
が成り立つ。

つまり、この状況では、$y$ がボルダ勝者であるとは断定できない。このケースで、多数決勝者がボルダ勝者であると断定できるのは、その選択肢が全票を集めた場合に限る。

ボルダはこの不一致が、選択肢の数が有権者の数を上回るときは、常に起こりうることを示した。

*Theorem 2*\\
有権者の数を $n$ 、選択肢の数を $m$ とし、 $n < m$ が成り立つとする。いま、多数決のもとで、 $n-1$ の有権者が $y$ に投票し、残る1人が $x$ に投票し、 $y$ が多数決勝者となるものとすると、 $y$ がボルダ勝者であるとは断定できない。
\\
*[Proof]* \\
いま $n-1$ 人が $y$ に投票し、残る1人が $x$ に投票するということは
|               | 有権者 $1$ | 有権者 $2$ | $\cdots$ | 有権者 $n-1$ | 有権者 $n$ |
|---------------+------------+------------+----------+--------------+------------|
| /             | <>         | <>         | <>       | <>           | <>         |
| 1位($m$ 点)   | $y$        | $y$        | $\cdots$ | $x$          | $x$        |
| 2位($m-1$ 点) | ?          | ?          | ?        | ?            | ?          |
| $\vdots$      |            |            |          |              |            |
| $m$ 位(1点)   | ?          | ?          | ?        | ?            | ?          |

のようなケースだということである。よって、以下の状況も起こりうる
|               | 有権者 $1$ | 有権者 $2$ | $\cdots$ | 有権者 $n-1$ | 有権者 $n$ |
|---------------+------------+------------+----------+--------------+------------|
| /             | <>         | <>         | <>       | <>           | <>         |
| 1位($m$ 点)   | $y$        | $y$        | $\cdots$ | $x$          | $x$        |
| 2位($m-1$ 点) | ?          | ?          | ?        | ?            | ?          |
| $\vdots$      |            |            |          |              |            |
| $m$ 位(1点)   | ?          | ?          | ?        | ?            | $y$        |

このとき、 $m > n$ より、
\begin{eqnarray}
\label{eq:5}
p(y) - p(x) & = & (n-1)m + 1 - (n-1)(m-1) - m \nonumber\\
            & = & n - m < 0
\end{eqnarray}

よって、 $y$ はボルダ勝者ではない。\\
$\square$

この定理から、「$n<m$ のときに多数決勝者がボルダ勝者と断定できるのは、全員一致の支持を得た場合のみに限る」ということがわかる。
** 1.1.3 ボルダルールの戦略的操作
戦略的投票に関する指摘について。
3人の有権者がいる、次の状況を考える。
|          | クロ | タマ | ポチ |
|----------+------+------+------|
| /        | <>   | <>   | <>   |
| 1位(4点) | $x$  | $y$  | $y$  |
| 2位(3点) | $y$  | $x$  | $x$  |
| 3位(2点) | $z$  | $z$  | $z$  |
| 4位(1点) | $w$  | $w$  | $w$  |

ここで、 $p(x) = 10, p(y) = 11, p(z) = 6, p(w) = 3$ であり、 $y$ がボルダ勝者となる。

$x$ を最も高く評価するクロにとってこの結果は好ましくない。しかし、もしクロが戦略的に虚偽の順序付けして
|          | クロ | タマ | ポチ |
|----------+------+------+------|
| /        | <>   | <>   | <>   |
| 1位(4点) | $x$  | $y$  | $y$  |
| 2位(3点) | $z$  | $x$  | $x$  |
| 3位(2点) | $w$  | $z$  | $z$  |
| 4位(1点) | $y$  | $w$  | $w$  |

となった場合には、 $p(x) = 10, p(y) = 9, p(z) = 7, p(w) = 4$ であり、ボルダ勝者は $x$ へと変わる。これはクロにとって望ましい結果だ。

もう一つの例として
|          | クロ | タマ | ポチ |
|----------+------+------+------|
| /        | <>   | <>   | <>   |
| 1位(3点) | $x$  | $y$  | $y$  |
| 2位(2点) | $z$  | $x$  | $x$  |
| 3位(1点) | $y$  | $z$  | $z$  |

を考える。この場合、 $p9x) = 7, p(y) = 7, p(z) = 4$ であり、ボルダ勝者は $x,y$ になる。

ここで、タマが戦略的に虚偽の投票をすることによって
|          | クロ | タマ | ポチ |
|----------+------+------+------|
| /        | <>   | <>   | <>   |
| 1位(3点) | $x$  | $y$  | $y$  |
| 2位(2点) | $z$  | $z$  | $x$  |
| 3位(1点) | $y$  | $x$  | $z$  |
となった場合、 $p(x) = 6, p(y) = 7, p(z) = 5$ であり、ボルダ勝者は $y$ となる。

つまり、$y$ を最も高く評価するタマは、 $y$ のライバルである $x$ を最下位に順序つけることによって、 $x$ ボルダ勝者の座から蹴落とすことができる。

この戦略的操作による影響は、現在考えられているどのような集約ルールについても完全に排除できないことが知られている。（ギバート＝サタスウェイト定理）
** 1.2 コンドルセの考察を巡って
** 1.2.1 コンドルセと一般意志
コンドルセについて
- M.J.A.N. Condorcet (1743-1794, コンドルセ)はパリ王立科学アカデミーの代表的な学者だった。数学への貢献によりアカデミーに入会。
- 数理分析を本格的に用いる社会科学の創始者の一人。
- 革命前には政治に関わり自由主義的な経済政策を推し進め、革命後は民主的な社会を強く思考する憲法草案を起草した。
- 公教育の重要性も論じた。
- その他、活動は多岐にわたる。
- コンドルセはルソー(Rouseau)の影響を強く受けた啓蒙思想(Lumieres)の理論化であり実践化であった。

1.1節で扱ったボルダ論文は、1770年にパリ王立科学アカデミーで発表した内容をまとめたものである。
この論文は1781年のアカデミー機関誌に解析(analyse)の分類で掲載され、1784年に出版された。
この掲載に、コンドルセが編集者として関わっており、彼によるボルダ論文の解説が収められている。
そこで彼は、多数決について、ボルダと同じような指摘をする。（ペア全敗者が多数決勝者になってしまうケースの指摘）

|     | 8 人 | 7 人 | 6 人 |
|-----+------+------+------|
| /   | <>   | <>   | <>   |
| 1位 | $x$  | $y$  | $z$  |
| 2位 | $z$  | $z$  | $y$  |
| 3位 | $y$  | $x$  | $x$  |

コンドルセは、選択肢が3つ以上の場合、多数決のようにペア全敗者を選ぶようなルールをはやめて、より望ましいものを探そうというモチベーションをボルダと深く共有している。

ボルダはそこで、ボルダルールを提案することで問題の解決を試みるが、コンドルセはそれとは異なる立場をとる。（ボルダの事は高く評価している）

コンドルセは集約ルールに対して、 *ペア全敗者を選ばないことのみならず、ペア全勝者が存在する場合には、それを選び取ること* を求めた。

*ペア全勝者* とは、他のどの選択肢に対しても、ペア毎の多数決で勝てる選択肢のこと。上記の例だと、$z$ がペア全勝者。

ここでのボルダ得点は
\begin{eqnarray*}
\label{eq:6}
p(x) & = & 37\\
p(y) & = & 41\\
p(z) & = & 48
\end{eqnarray*}
なのでペア全勝者の $z$ を選べている。しかし、この事は常には成り立たない、というのがコンドルセがボルダルールを否定する理由であった。

1.1節で出てきた下の例で見ると
|          | クロ | タマ | ポチ | ゴマ | ケロ |
|----------+------+------+------+------+------|
| /        | <>   | <>   | <>   | <>   | <>   |
| 1位(3点) | $y$  | $y$  | $y$  | $x$  | $x$  |
| 2位(2点) | $x$  | $x$  | $x$  | $z$  | $z$  |
| 3位(1点) | $z$  | $z$  | $z$  | $y$  | $y$  |
\begin{eqnarray*}
\label{eq:7}
p(x) & = & 12\\
p(y) & = & 11\\
p(z) & = & 7
\end{eqnarray*}
なので、 $x$ がボルダ勝者であるが、 ペア全勝者は $y$ である。すなわち、ボルダルールはペア全勝者を選ぶことに失敗している。

コンドルセは、同様の失敗が、あらゆるスコアリングルールで起こりうることを示した。

スコアリングルールとは、各選挙人が $m$ 個の選択肢に対して、好ましい順に $a_{1} > a_{2} > \cdots > a_{m}$ という得点をつけて、その得点和で総合順位を決める集約ルールのことである。
例えば
|                  | クロ | タマ | ポチ | ゴマ | ケロ |
|------------------+------+------+------+------+------|
| /                | <>   | <>   | <>   | <>   | <>   |
| 1位( $a_{1}$ 点) | $y$  | $y$  | $y$  | $x$  | $x$  |
| 2位( $a_{2}$ 点) | $x$  | $x$  | $x$  | $z$  | $z$  |
| 3位( $a_{3}$ 点) | $z$  | $z$  | $z$  | $y$  | $y$  |

における各選択肢の得点は
\begin{eqnarray*}
\label{eq:8}
p(x) & = & 2a_{1} + 3 a_{2}\\
p(y) & = & 3a_{1} + 2a_{3}\\
p(z) & = & 2s_{2} + 3a_{3}
\end{eqnarray*}
である。ボルダルールは $a_{i} = i$ としたスコアリングルールである。

*Theorem 3* \\
ペア全勝者が存在するにもかかわらず、どのスコアリングルールもそれを選び取れない状況がある。\\
*Proof*\\
コンドルセはこの定理を、81人の有権者が存在する下の例を用いて証明した。
|                  | 30人 | 1人 | 29人 | 10人 | 10人 | 1人 |
|------------------+------+-----+------+------+------+-----|
| /                | <>   | <>  | <>   | <>   | <>   | <>  |
| 1位( $a_{1}$ 点) | $x$  | $x$ | $y$  | $y$  | $z$  | $z$ |
| 2位( $a_{2}$ 点) | $y$  | $z$ | $x$  | $z$  | $x$  | $y$ |
| 3位( $a_{3}$ 点) | $z$  | $y$ | $z$  | $x$  | $y$  | $x$ |

いま、ペア同士の多数決では41対40で $x$ が $y$ に勝ち、60対21で $x$ が $z$ に勝つので、$x$ がペア全勝者である。

一方で、
\begin{eqnarray*}
\label{eq:9}
p(x) & = & 31a_{1} + 39 a_{2} + 11a_{3}\\
p(y) & = & 39a_{1} + 31a_{2} + 11a_{3}\\
p(z) & = & 11a_{1} + 11s_{2} + 59a_{3}
\end{eqnarray*}
なので、 $a_{1} > a_{2} > a_{3}$ である限り、
\begin{eqnarray*}
\label{eq:10}
p(y) - p(x) & = & 8(a_{1} - a_{2})>  0 \\
p(x) - p(z) & = & 20a_{1} + 28a_{2} - 48a_{3} > 48(a_{2} - a_{3}) > 0
\end{eqnarray*}
よって、 $p(y) > p(x) > p(z)$ が成り立つ。\\
つまり、どのスコアリングルールでも $y$ を1位とするので、$x$ は選ばれない。 $\square$

この定理は、各選択肢に得点を割り振ってその総和により社会的選択を行うという、ボルダの発想の核心を否定するものだ。
この延長線上として、コンドルセは、それぞれの選択肢が「選択肢全体の中で」どの順位を与えられているかという観点を、意思集約から除外することを試みた。

具体的には、2つの選択肢についてそれぞれ多数決を行い、それらのショ結果を組み合わせて全体の判断を行うという研究プログラムの形をとることになる。
*** コンドルセの方法　選択肢が３つの場合の例
いま、有権者が13人として、3つの選択肢 $x,y,z$ のうちそれぞれ2つに対し総当り戦でペア毎の多数決を行い、次の結果が得られたとしよう。
|     | $x$ | $y$ | $z$ |
|-----+-----+-----+-----|
| /   | <>  | <>  | <>  |
| $x$ | -   | 8   | 6   |
| $y$ | 5   | -   | 11  |
| $z$ | 7   | 2   | -   |

読み方:
- $x$ 対 $y$ では、 8:5 で $x$ が勝つ
- $z$ 対 $x$ では、 7:6 で $z$ が勝つ
- $y$ 対 $z$ では、 11:2 で $y$ が勝つ

ここでは、ペア毎の多数決で循環が生じている。これを *コンドルセサイクル* という（あるいは単に *サイクル* ）。

このサイクルをどうにか崩さなければならない。

そこで、コンドルセは、最も票差が小さな「7:6 で $z$ が $x$ に勝つ」を結果から消去することを提案した( *コンドルセの方法* )。

すると、
- $x$ 対 $y$ では、 8:5 で $x$ が $y$ に勝つ
- $y$ 対 $z$ では、 11:2 で $y$ が $z$ に勝つ
ので、全体の順位が $xyz$ と決まり、勝者は $x$ となる。

選択肢が3つの場合、この方法は、明瞭であり、得票差の小さな結果を無視するのは、直感的にも納得しやすい。

しかし、コンドルセにとっては、これは単なる直感以上のもので、「得票差の大きい結果は正しい可能性が高い」という考えに基づいている。
この「正しい」という表現は、コンドルセの問題意識を表している。
*** ルソーの一般意志
ルソーの『社会契約論(仏:Du Contrat Social; ou, Principes du droit, 英:The Social Contract) politique』[[https://en.wikipedia.org/wiki/The_Social_Contract#:~:text=The%20Social%20Contract%20helped%20inspire,have%20that%20all%2Dpowerful%20right.
]]では、一般意志(仏:volonté générale, 英:general will)という、ある種の共通利益を尊重することが重んじられる。
ルソーは一般意志と合致する選択肢を、人民の集会で多数決により探し当てることを考える。
そこでは各人は「私的利益に基づき何かを好む」ではなく、「私的立場を離れたうえでの、何が正しい可への判断」を表明することが求められる。

そしてルソーは「もし私の表明したことが多数決の結果と異なっているのならば、それは私が間違っていたことを意味しており、私が一般意志だと思っていたことがそうではなかったのだ」と論じている（第4篇、第2章）。

コンドルセはルソー的な意思集約を念頭に置いており、一般意志に合致する選択肢を見つける手段を見つけるのが彼の投票研究の問題意識であったと考えられる。

コンドルセ「これは渡井自身ではなく、全員にとっての問なのだ。つまり私は、私が単に良いと思うものを選ぶべきではない。各自固有の意見から抜け出た人々が理性と心理に適合すると考えるもの、を選ばねばならない」

一般意志に適うものがなにであるかは、最初から明らかなわけではない。
それゆえ、一般意志に合致する選択肢の探索手段としてルソーは投票を考えていたし、その考えを引き継いだコンドルセにとって、正しい可能性が高い選択肢を探すのは本質的なことであった。
*** コンドルセの方法の瑕疵
コンドルセの方法は、選択肢が3つのときは簡単に実行できる。ペア全勝者が存在する場合には、それを選び取ればよい。
だが、選択肢が4つ以上存在するとき、この方法は必ずしもうまく機能しないことが、指摘された(Nanson, Black)。以下は Young による例。

|     | $x$ | $y$ | $z$ | $w$ |
|-----+-----+-----+-----+-----|
| /   |  <> |  <> |  <> |  <> |
| $x$ |   - |  12 |  15 |  17 |
| $y$ |  13 |   - |  16 |  11 |
| $z$ |  10 |   9 |   - |  18 |
| $w$ |   8 |  14 |   7 |   - |

多数決の結果は
- 13 : 12 で $y$ が $x$ に勝つ
- 15 : 10 で $x$ が $z$ に勝つ
- 17 : 8 で $x$ が $w$ に勝つ
- 16 : 9 で $y$ が $z$ に勝つ
- 14 : 11 で $w$ が $y$ に勝つ
- 18 : 7 で $z$ が $w$ に勝つ
となり、 サイクル $yxzwy$ が発生している。

ここから、最も得票差が小さい「13 : 12 で $y$ が $x$ に勝つ」を消去するとサイクル $yzwy$ が残る。

次に得票差が小さな結果である「14 : 11 で $w$ が $y$ に勝つ」を消去すると、
- 15 : 10 で $x$ が $z$ に勝つ
- 17 : 8 で $x$ が $w$ に勝つ
- 16 : 9 で $y$ が $z$ に勝つ
- 18 : 7 で $z$ が $w$ に勝つ
こととなり、これでサイクルはなくなった。しかし、残った結果からは、 $x$ と $y$ のどちらを上位にするかは確定できない。
これが、コンドルセの方法が上手くいかない例である。
** 1.2.2 2択問題における多数決の優位性
社会的選択に関するコンドルセの議論：
ある裁判の被告に対し、一人ひとりの有権者が独立に、「有罪」であるか「無罪」であるか判断して、いずれかに票を入れる多数決を考えて見よう。

有罪と無罪、どちらが正しいかは完全にはわからない。

有権者が、有罪と無罪を正しく判断できる確率が全有権者で同じ $0.5 < v \le 1$ であると仮定しよう。

これは、人間の判断が、完全にランダムな判断 $v = \frac{1}{2}$ よりは、制度が高いことを仮定している。

このかていのもと、3人の有権者が、それぞれ、独立に判断を行い、多数決を取った結果が正しい確率は

\begin{equation}
\label{eq:11}
v^{3} + 3v^{2}(1-v)
\end{equation}
である。
*Theorem 4* \\
$0.5 < v < 1$ ならば
\begin{equation}
\label{eq:12}
v^{3} + 3v^{2}(1-v) > v
\end{equation}
が成り立つ。すなわち、3人による多数決の結果が正しい確率は、一人が正しい確率を上回る。\\
*Proof*\\
$0.5 < v < 1$ であるから、
\begin{eqnarray}
\label{eq:13}
v^{3} + 3v^{2}(1-v) - v& = & v\{v^{2} + 3v(1-v) - 1\} \nonumber\\
                    & = & v(-2v^{2} + 3v - 1) \nonumber\\
                    & = & v(-2v + 1)(v - 1) \nonumber \\
                    & = & -2v(v - \frac{1}{2})(v - 1) > 0 \nonumber
\end{eqnarray}
$\square$
